### PR TITLE
added password page

### PR DESCRIPTION
**Pull request by anujparakh**
Added

### CODE REVIEW

**Comment by jNLeee** [comment]
Everything is running and looks good!

**Review by jNLeee — APPROVED** [review]
Everything looks good and looks ready to merge!

**Comment by BrentonLenzen** [comment]
Everything looks good to me.

**Review by BrentonLenzen — APPROVED** [review]
Everything looks good to me.

**Comment by Amg9973** [comment]
Everything looks good, ready to merge.

**Review by Amg9973 — COMMENTED** [review]
Everything looks good, ready to merge.

**Pull request merged**
