### PR TITLE
Semesters and member add

### PR DESCRIPTION
**Pull request by BrentonLenzen**
Created semester CRUD page and add page for members.

### CODE REVIEW

**Comment by jNLeee** [comment]
Everything is running and looks good!

**Comment by jNLeee** [comment]
Everything looks good and looks ready to merge!

**Review by anujparakh — APPROVED** [review]
Looks good to merge

**Comment by Amg9973** [comment]
Everything looks good, ready to merge.

**Review by Amg9973 — COMMENTED** [review]
Everything looks good, ready to merge.

**Review by anujparakh — COMMENTED** [review]
Might wanna work on formatting - 2 spaces for the tabs is the code standard

**Pull request merged**
